---
base-size: 16
default-family: 'default'
fallback-family: ['Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif']

weights:
    regular: 400

sizes:
    default:
        normal: ['Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif']
        xxlarge:
            font-size: 35
            line-height: 40
        xlarge:
            font-size: 30
            line-height: 35
        large:
            font-size: 20
            line-height: 25
        base:
            font-size: 17
            line-height: 23
        small:
            font-size: 15
            line-height: 20
        xsmall:
            font-size: 12
            line-height: 15
